(defpackage llace/tests/parsing
  (:use :cl :serapeum :parachute :llace/functional-parsing :llace/parsing)
  (:shadowing-import-from :parachute :true))
(in-package :llace/tests/parsing)

(define-test nat
  (is equal '() (parse (llace/parsing::nat) ""))
  (is equal '((1 . "")) (parse (llace/parsing::nat) "1"))
  (is equal '() (parse (llace/parsing::nat) "-1"))
  (is equal '((123 . "")) (parse (llace/parsing::nat) "123"))
  (is equal '() (parse (llace/parsing::nat) "-123"))
  (is equal '((123 . "abc")) (parse (llace/parsing::nat) "123abc"))
  (is equal '() (parse (llace/parsing::nat) "-123abc"))
  (is equal '() (parse (llace/parsing::nat) "abc123")))

(define-test int
  (is equal '() (parse (llace/parsing::int) ""))
  (is equal '((1 . "")) (parse (llace/parsing::int) "1"))
  (is equal '((-1 . "")) (parse (llace/parsing::int) "-1"))
  (is equal '((123 . "")) (parse (llace/parsing::int) "123"))
  (is equal '((-123 . "")) (parse (llace/parsing::int) "-123"))
  (is equal '((123 . "abc")) (parse (llace/parsing::int) "123abc"))
  (is equal '((-123 . "abc")) (parse (llace/parsing::int) "-123abc"))
  (is equal '() (parse (llace/parsing::int) "abc123")))

(define-test spacing
  (is equal '((() . "")) (parse (llace/parsing::spacing) ""))
  (is equal '((() . "")) (parse (llace/parsing::spacing) " "))
  (is equal '((() . "")) (parse (llace/parsing::spacing) "	"))
  (is equal '((() . "")) (parse (llace/parsing::spacing) "   	"))
  (is equal '((() . "foo  	")) (parse (llace/parsing::spacing) "   	foo  	")))

(define-test a-natural
  (is equal '() (parse (llace/parsing::a-natural) ""))
  (is equal '((1 . "")) (parse (llace/parsing::a-natural) "1"))
  (is equal '((1 . "")) (parse (llace/parsing::a-natural) "  1	"))
  (is equal '() (parse (llace/parsing::a-natural) "-1"))
  (is equal '((123 . "")) (parse (llace/parsing::a-natural) "123"))
  (is equal '((123 . "")) (parse (llace/parsing::a-natural) "	 123   "))
  (is equal '() (parse (llace/parsing::a-natural) "-123"))
  (is equal '((123 . "abc")) (parse (llace/parsing::a-natural) "123abc"))
  (is equal '((123 . "abc")) (parse (llace/parsing::a-natural) " 123	abc"))
  (is equal '() (parse (llace/parsing::a-natural) "-123abc"))
  (is equal '() (parse (llace/parsing::a-natural) "abc123")))

(define-test an-integer
  (is equal '() (parse (llace/parsing::an-integer) ""))
  (is equal '((1 . "")) (parse (llace/parsing::an-integer) "1"))
  (is equal '((1 . "")) (parse (llace/parsing::an-integer) "   1 	 "))
  (is equal '((-1 . "")) (parse (llace/parsing::an-integer) "-1"))
  (is equal '((-1 . "")) (parse (llace/parsing::an-integer) "	 -1  "))
  (is equal '((123 . "")) (parse (llace/parsing::an-integer) "123"))
  (is equal '((123 . "")) (parse (llace/parsing::an-integer) "  123	 "))
  (is equal '((-123 . "")) (parse (llace/parsing::an-integer) "-123"))
  (is equal '((-123 . "")) (parse (llace/parsing::an-integer) " 	 -123    "))
  (is equal '((123 . "abc")) (parse (llace/parsing::an-integer) "123abc"))
  (is equal '((123 . "abc")) (parse (llace/parsing::an-integer) "	123 abc"))
  (is equal '((-123 . "abc")) (parse (llace/parsing::an-integer) "-123abc"))
  (is equal '((-123 . "abc")) (parse (llace/parsing::an-integer) "    -123	abc"))
  (is equal '() (parse (llace/parsing::an-integer) "abc123")))

(define-test a-character
  (is equal '() (parse (llace/parsing::a-character #\-) ""))
  (is equal '() (parse (llace/parsing::a-character #\-) "1"))
  (is equal '() (parse (llace/parsing::a-character #\-) "a"))
  (is equal '() (parse (llace/parsing::a-character #\-) "_"))
  (is equal '((#\- . "")) (parse (llace/parsing::a-character #\-) "-"))
  (is equal '((#\- . "")) (parse (llace/parsing::a-character #\-) "	 - 	"))
  (is equal '((#\- . "1")) (parse (llace/parsing::a-character #\-) "-1"))
  (is equal '((#\- . "1")) (parse (llace/parsing::a-character #\-) "	-   1"))
  (is equal '((#\- . "123")) (parse (llace/parsing::a-character #\-) "-123"))
  (is equal '((#\- . "123")) (parse (llace/parsing::a-character #\-) " -	123")))

(define-test a-symbol
  (is equal '() (parse (llace/parsing::a-symbol "let") ""))
  (is equal '() (parse (llace/parsing::a-symbol "let") "l"))
  (is equal '() (parse (llace/parsing::a-symbol "let") "le"))
  (is equal '(("let" . "")) (parse (llace/parsing::a-symbol "let") "let"))
  (is equal '(("let" . "")) (parse (llace/parsing::a-symbol "let") "  	let 	"))
  (is equal '() (parse (llace/parsing::a-symbol "let") "leet"))
  (is equal '(("let" . "me")) (parse (llace/parsing::a-symbol "let") "letme"))
  (is equal '(("let" . "me")) (parse (llace/parsing::a-symbol "let") " 	let  me"))
  (is equal '(("let" . "x = 42;")) (parse (llace/parsing::a-symbol "let") "let x = 42;"))
  (is equal '(("let" . "x = 42;")) (parse (llace/parsing::a-symbol "let") "	let  x = 42;")))

(define-test expr
  (is equal '((4 . "")) (parse (expr) "2 + 2"))
  (is equal '((4 . "")) (parse (expr) "2 +2"))
  (is equal '((4 . "")) (parse (expr) " 2 +2"))
  (is equal '((4 . "")) (parse (expr) "2+2"))
  (is equal '((4 . "")) (parse (expr) "2 + (2)"))
  (is equal '((4 . "")) (parse (expr) "(2) + (2)"))
  (is equal '((4 . "")) (parse (expr) "((2) + (2))"))
  (is equal '((4 . "")) (parse (expr) " ( (2) + (2) ) "))
  (is equal '((10 . "")) (parse (expr) "2 + 2 * 4"))
  (is equal '((10 . "")) (parse (expr) "( 2+2*4 )"))
  (is equal '((16 . "")) (parse (expr) "(2 + 2) * 4"))
  (is equal '((16 . "")) (parse (expr) "(2 + 2 * 1) * 4"))
  (is equal '((10 . "")) (parse (expr) "(2 + 2 * 1) * 2 + 1 + 1"))
  (is equal '((13 . "")) (parse (expr) "(2 + 2 * 1) * (2 + 1) + 1")))
